### ISSUE TITLE
Temporal.Now.plainDateISO() & plainTimeISO throw undefined timezone

### ISSUE THREAD

**Issue by rektide** [js-temporal/temporal-polyfill#147]
# Reproduction Steps:

Try to call `Temporal.Now.plainDateISO()`.

# Expected Results:

According to https://tc39.es/proposal-temporal/docs/now.html#plainDateISO , it should give a PlainDate.

# Actual Results:

```
Uncaught RangeError: Invalid time zone: undefined
    at ParseTemporalTimeZoneString (file:///home/rektide/src/week-of-year/node_modules/@js-temporal/polyfill/dist/index.esm.js:2794:11)
    at ParseTemporalTimeZone (file:///home/rektide/src/week-of-year/node_modules/@js-temporal/polyfill/dist/index.esm.js:2582:35)
    at SystemTimeZone (file:///home/rektide/src/week-of-year/node_modules/@js-temporal/polyfill/dist/index.esm.js:5965:33)
    at timeZone (file:///home/rektide/src/week-of-year/node_modules/@js-temporal/polyfill/dist/index.esm.js:7975:12)
    at Temporal.Now.plainDateISO (file:///home/rektide/src/week-of-year/node_modules/@js-temporal/polyfill/dist/index.esm.js:7968:46)
```

Tested on Node v16.14.0.

# Workaround

Explicitly specify a timezone name: `Temporal.Now.plainDateISO('GMT')`. This will return a PlainDate.

**Comment by pmcelhaney** [comment]
I think you meant to link this part of the docs. https://tc39.es/proposal-temporal/docs/now.html#plainDateISO

**Comment by justingrant** [comment]
This looks like an environment-specific problem, because it doesn't repro locally for me nor does it cause test failures (locally or in CI) for this test: https://github.com/js-temporal/temporal-polyfill/blob/2f6e6b43267113a213d08b70be8ea72e8075aa1a/test/now.mjs#L92-L96

Could you share the command line args that you're using to launch Node?

To dig into the most likely reason for the failures you're seeing in your environment, look at `SystemTimeZone` function https://github.com/js-temporal/temporal-polyfill/blob/2f6e6b43267113a213d08b70be8ea72e8075aa1a/lib/ecmascript.ts#L5245-L5249

Stripping all the Temporal-specific code away, the core of that function is this: 

```js
new Intl.DateTimeFormat('en-us').resolvedOptions().timeZone
```

Could you try running the line of code above in your environment (but without this polyfill loaded) and let us know what the result is?  If it's `undefined`, then the problem doesn't seem to be Temporal-related. Any API that uses `Intl` to get the system time zone will also fail. You should investigate why your environment has an undefined system time zone.  

However, if it's not `undefined`, then try this code: 

```js
import { Intl } from '@js-temporal/polyfill';
new Intl.DateTimeFormat('en-us').resolvedOptions().timeZone
```

This is the same as the first code except it's using the `Intl.DateTimeFormat` polyfill. If the first code snippet returned a non-`undefined` value but the polyfilled one returns an `undefined`, then it may be a bug in the `Intl` portion of this polyfill. 

If both code snippets return a not-`undefined` value, then it may be a polyfill bug although we'd need to investigate more to find out why.

**Comment by rektide** [comment]
I was on a new-ish system & had not set a timezone via `timedatectl set-timezone`. Things started working ok when I set a timezone.

I'm ok with things as they are. There's a debatable possible merit to defaulting to UTC & not crashing, but I'm past this & have left this linger a while already. Thank you for the really good in depth debugging help all; apologies and thanks.

**Comment by justingrant** [comment]
> There's a debatable possible merit to defaulting to UTC & not crashing

This seems reasonable since the only case where I could imagine a timezone not existing would be custom-built servers. Consumer PCs and phones would always have a time zone. 

But this isn't a Temporal-specific thing so I don't know whether that solution would be a good one or not. You may want to file an issue in the `Intl` spec repo (https://github.com/tc39/ecma402) where the experts can discuss the merits.
