### ISSUE TITLE
Temporal.TimeZone.from incorrect return type

### ISSUE THREAD

**Issue by Darkhogg** [js-temporal/temporal-polyfill#171]
According to the [documentation](https://tc39.es/proposal-temporal/docs/timezone.html#from), `Temporal.TimeZone.from` should return a `TimeZone`, but in this polyfill it's defined as returning `TimeZone | TimeZoneProtocol`.

**Comment by ptomato** [comment]
Thanks for taking the time to open an issue! It's appreciated.

You can read about this in the [Custom Time Zones](https://tc39.es/proposal-temporal/docs/timezone.html#custom-time-zones) section — plain objects implementing certain methods (called `TimeZoneProtocol` in the TypeScript definitions) are allowed to be time zones as well.

A plain object as a time zone is a very rare, specialized use case so that's why we don't mention it directly in the documentation, other than in the Custom Time Zones section. If we mentioned it everywhere, it'd be more likely to confuse people or make them think they might need to use that feature when most likely they don't.

We could probably make the signature of `Temporal.TimeZone.from` more accurate, e.g. something like
```ts
static from<T extends Object>(timeZoneLike: T): T;
static from(timeZoneLike: TimeZoneLike): TimeZone;
```
(although I'm not exactly sure how to express this in TypeScript)

Feel free to submit a PR to either the TypeScript definitions or the documentation to make this clearer.

**Comment by Darkhogg** [comment]
Shouldn't `.from` always return a `TimeZone`, though? Other methods accepting `TimeZoneProtocol` or `TimeZoneLike` seems fine, but in my mind a ' .from'  is to convert to the class (and that's what the documentation suggests to me), I might just be wrong.

**Comment by ptomato** [comment]
Oh, I guess what I wrote is not quite correct though, because if you pass a ZonedDateTime you'll get its `timeZone` property.
