### ISSUE TITLE
Chaining `subtract` on `PlainYearMonth` leads to a lock 

### ISSUE THREAD

**Issue by mijamo** [js-temporal/temporal-polyfill#44]
I am not sure what the cause of this issue is but look at the following:

```
const month = Temporal.PlainYearMonth.from(Temporal.Now.plainDate('gregory', 'Europe/Stockholm')) // Temporal.PlainYearMonth <2021-09-01[u-ca=gregory]>
month.subtract({months: 5}) // Temporal.PlainYearMonth <2021-04-01[u-ca=gregory]>
month.subtract({months: 1}).subtract({months: 1}).subtract({months: 1}) // Temporal.PlainYearMonth <2021-07-01[u-ca=gregory]>, but expected 2021-06-01 instead
month.subtract({months: 1}).subtract({months: 1}).subtract({months: 5}) // still 2021-07-01, at this point it is "locked" and subtracting will always keep the month as 07
```

It seems like for some reason the chain leads to some state where it is not possible to subtract months anymore,.

**Comment by justingrant** [comment]
@mijamo - What version of the polyfill are you using?  Given that this bug doesn't repro in the current `main` branch, I assume it's a bug that was already fixed in main but hasn't made it out to an npm release yet. 

Here's what I see on the latest `main` branch of this repo using `npm run playground` (you'll need to add a `toString()` call at the end of each line to avoid errors in the REPL).
```js
> const month = Temporal.PlainYearMonth.from(Temporal.Now.plainDate('gregory', 'Europe/Stockholm'))
undefined
> month.toString()
'2021-09-01[u-ca=gregory]'
> month.subtract({months: 5}).toString()
'2021-04-01[u-ca=gregory]'
> month.subtract({months: 1}).subtract({months: 1}).subtract({months: 1}).toString()
'2021-06-01[u-ca=gregory]'
> month.subtract({months: 1}).subtract({months: 1}).subtract({months: 5}).toString()
'2021-02-01[u-ca=gregory]'
```

If you can repro this on top of the latest main branch, let us know. Otherwise it should be fixed with the next npm release, which should be soon after we get a few pending PRs merged to catch up with the latest changes from proposal-temporal.

**Comment by mijamo** [comment]
I was using the latest NPM version (0.2.0)-

Using your method it works on `main` so I will close this issue and wait for the new NPM release then.
